pae

diff --git a/bin/run_tests b/bin/run_tests
--- a/bin/run_tests
+++ b/bin/run_tests
@@ -1,3 +1,4 @@
+
 #!/bin/bash -u
 
 #-u means:
@@ -72,20 +73,6 @@ fi
 cd "$_current_user_dir"
 eval `globalize _bohem_dir`  #change _bohem_dir after this function working with eval
 
-#stop all processes
-trap finish SIGHUP SIGINT SIGTERM
-
-function finish (){
-   
-  echo "kill bohem process ..."
-  for process in $(ps -ef|grep "${_bohem_dir}" |awk '{print $2}')
-  do
-   echo "kill -9 " $process
-   kill -9 $process
-   done
-}
-
-export -f finish
 
 # Check installation. This sanity test must be at this point, as this path is
 # where the next things are read from.
@@ -129,7 +116,7 @@ fi
 source "${_bohem_dir}/etc/global.vars"
 
 export PYTHONPATH=${_bohem_dir}/lib/python:${PYTHONPATH:-}
-
+export PATH=$PATH:${_bohem_dir}:${_bohem_dir}/bin
 # Read in test-list variables.
 # This is a requested feature that I do not particularly like -> too much coding
 # for something that will be hardly used, if ever.
@@ -299,14 +286,76 @@ then
 	> "$ERRFILE"
 fi
 
-#finish
+#function collect final statistic
+
+function summary (){
+		##############################
+		#	COLLECT FINAL STATISTICS
+		##############################
+		
+		# Please note that the statistics are generated by counting the words "FAILED" and
+		# "PASSED" in LOGFILE, which were generated by the parse* duo based on the test
+		# case exit status. However, it is possible that individual tests could sneak this
+		# in as well, in which case the statistics would get slightly skewed.
+		printf "\n" >> "$LOGFILE"	# blank line
+		printf "Test-suite ended: %s\n" "$(date)" | tee -a "$LOGFILE"
+		printf "\n" >> "$LOGFILE"	# blank line
+		_passed=`grep -c '^PASSED:' "$LOGFILE"`
+		#_passed=`grep -c '^TESTPASSED:' "$LOGFILE"`
+		_failed=`grep -c '^FAILED:' "$LOGFILE"`
+		_broken=`grep -c '^BROKEN:' "$LOGFILE"`
+		
+		printf "bohem $_bohem_version Info:\n" | tee -a "$LOGFILE"
+		printf "\tEntire test-suite took $(( $SECONDS / 60 )) minutes.\n"\
+			| tee -a "$LOGFILE"
+		printf "\tTotal number of tests passed:\t${_passed}\n" | tee -a "$LOGFILE"
+		printf "\tTotal number of tests failed:\t${_failed}\n" | tee -a "$LOGFILE"
+		printf "\tTotal number of tests ran:\t$(( $_passed + $_failed ))\n" | tee -a "$LOGFILE"
+		printf "\tTotal number of tests broken:\t${_broken}\n\n" | tee -a "$LOGFILE"
+		
+		# Generate final message and exit.
+		if [ $_failed -ne 0 ]
+		then
+			printf "bohem $_bohem_version Info:\n"
+			printf "\tSOME TESTS FAILED. ($_failed)\n"
+			rm -rf ${_current_user_dir}/.bohem_pid/
+			#exit 0
+		fi
+		printf "bohem $_bohem_version Info:\n"
+		printf "\tALL TESTS PASSED. ($_passed)\n"
+		rm -rf ${_current_user_dir}/.bohem_pid/
+		#exit 0 
+}
+#stop all processes
+trap  force_stop   SIGHUP SIGINT SIGTERM
+
+function force_stop (){
+  
+  echo -e "\n\033[32m<<<<<<<<<< Killing all backend bohem processes ...\033[0m\n"
+  #rm -rf ${_current_user_dir}/.bohem_pid
+  summary
+  #for process in $(ps -ef|grep -E "run_tests|test_run|parse_and_execute|parse_test_list|tc_monitor|"|grep -iv "vi"|grep -iv "uex"|awk '{print $2}')
+  for process in $(ps -ef|grep -E "test_run|${_bohem_dir}"|grep -E "run_tests|test_run|parse_and_execute|parse_test_list|tc_monitor|"|grep -iv "vi"|grep -iv "uex"|awk '{print $2}')
+  do
+  	 echo "kill -9 " $process
+   	 kill -9 $process >/dev/null  2>&1 &  
+   	 #kill -9 0
+   	 #exit
+  done
+  echo
+  exit
+}
+
+export -f force_stop
+
+
 ##############################
 #	RUN THE TESTS
 ##############################
 
 for _test_list in "$@"
 do
-  echo ==$_test_list
+
 	# Test for lazy people.
 	if [ -x "${_test_list}" -a ! -d "${_test_list}" ]
 	then
@@ -329,40 +378,6 @@ done
 
 
 test -f $WORK_DIR/quit && rm $WORK_DIR/quit
-##############################
-#	COLLECT FINAL STATISTICS
-##############################
 
-# Please note that the statistics are generated by counting the words "FAILED" and
-# "PASSED" in LOGFILE, which were generated by the parse* duo based on the test
-# case exit status. However, it is possible that individual tests could sneak this
-# in as well, in which case the statistics would get slightly skewed.
-printf "\n" >> "$LOGFILE"	# blank line
-printf "Test-suite ended: %s\n" "$(date)" | tee -a "$LOGFILE"
-printf "\n" >> "$LOGFILE"	# blank line
-_passed=`grep -c '^PASSED:' "$LOGFILE"`
-#_passed=`grep -c '^TESTPASSED:' "$LOGFILE"`
-_failed=`grep -c '^FAILED:' "$LOGFILE"`
-_broken=`grep -c '^BROKEN:' "$LOGFILE"`
-
-printf "bohem $_bohem_version Info:\n" | tee -a "$LOGFILE"
-printf "\tEntire test-suite took $(( $SECONDS / 60 )) minutes.\n"\
-	| tee -a "$LOGFILE"
-printf "\tTotal number of tests passed:\t${_passed}\n" | tee -a "$LOGFILE"
-printf "\tTotal number of tests failed:\t${_failed}\n" | tee -a "$LOGFILE"
-printf "\tTotal number of tests ran:\t$(( $_passed + $_failed ))\n" | tee -a "$LOGFILE"
-printf "\tTotal number of tests broken:\t${_broken}\n\n" | tee -a "$LOGFILE"
-
-# Generate final message and exit.
-if [ $_failed -ne 0 ]
-then
-	printf "bohem $_bohem_version Info:\n"
-	printf "\tSOME TESTS FAILED. ($_failed)\n"
-	rm -rf ${_current_user_dir}/.bohem_pid/
-	exit 0
-fi
-printf "bohem $_bohem_version Info:\n"
-printf "\tALL TESTS PASSED. ($_passed)\n"
-rm -rf ${_current_user_dir}/.bohem_pid/
-exit 0 
-
+summary
+exit 0
